// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/greet.proto

/*
Package greet is a generated protocol buffer package.

It is generated from these files:
	proto/greet.proto

It has these top-level messages:
	GreetRequest
	GreetResponse
*/
package greet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GreetRequest) Validate() error {
	return nil
}
func (this *GreetResponse) Validate() error {
	return nil
}
